import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Servicing Packages: </h1>

        <br />

        <div className={styles.grid}>
          {/* SHELL PACKAGE */}
          <button
            className={styles.card}
            onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MZ1B8GQwZ3hbkvU41dYUGsw",
                    quantity: 1,
                  },
                ],
              });
            }}
          >
            <a>
              <h2>Shell Service Package</h2>
              <h3>$128.00</h3>
              <p>Fully synthetic 5W30 Engine oil 4L (Basic)</p>
              <p>Oil filter- OEM</p>
              <p>33 points check</p>
            </a>
          </button>

          {/* MOBIL PACKAGE */}
          <button
            className={styles.card}
            onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MZ1C8GQwZ3hbkvUfOmyhNxA",
                    quantity: 1,
                  },
                ],
              });
            }}
          >
            <a>
              <h2>Mobil Service Package</h2>
              <h3>$138.00</h3>
              <p>Fully synthetic 5W30 Engine oil 4L (USA)</p>
              <p>Oil filter- OEM</p>
              <p>33 points check</p>
            </a>
          </button>

          {/* CASTROL PACKAGE */}
          <button
            className={styles.card}
            onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MZ1CQGQwZ3hbkvUMGWVciUo",
                    quantity: 1,
                  },
                ],
              });
            }}
          >
            <a>
              <h2>Castrol Service Package</h2>
              <h3>$148.00</h3>
              <p>Fully synthetic 5W30 Engine oil 4L (France)</p>
              <p>Oil filter- OEM</p>
              <p>33 points check</p>
            </a>
          </button>

          {/* CASTROL PACKAGE */}
          <button
            className={styles.card}
            onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MZ1CnGQwZ3hbkvUXDpMeFu9",
                    quantity: 1,
                  },
                ],
              });
            }}
          >
            <a>
              <h2>LiquidMoly Service Package</h2>
              <h3>$158.00</h3>
              <p>Fully synthetic 5W30 Engine oil 4L (Germany)</p>
              <p>Oil filter- OEM</p>
              <p>33 points check</p>
            </a>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
